[package]
name = "client"
version = "0.1.0"
authors = ["Chris Holcombe <xfactor973@gmail.com>"]

[dependencies]
api = { path = "../api", version = "*"}
clap = "*"
log = "*"
protobuf = "*"
simplelog = "*"
zmq = "*"
